[project]
name = "ragprd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arize-phoenix-otel>=0.17.2",
    "docling>=2.131.0",
    "google-genai>=2.25.0",
    "httpx>=0.28.1",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "qdrant-client>=1.19.1",
    "requests>=2.34.2",
]
